name = "Default"
bg = "Reset"
fg = "White"
border = "Plain"
border_color = "White"
border_focused_color = "LightCyan"
hl_bg = "DarkGray"
solid_bg = "White"
solid_fg = "Black"
trusted = "Green"
remake = "Red"
