name = "Dracula"
bg = "#282A36"
fg = "#f8f8f2"
border = "Rounded"
border_color = "#6272a4"
border_focused_color = "#bd93f9"
hl_bg = "#6272a4"
solid_fg = "#282a36"
solid_bg = "#8be9fd"
trusted = "#50fa7b"
remake = "#ff5555"
