name = "Gruvbox"
bg = "#282828"
fg = "#ebdbb2"
border = "Plain"
border_color = "#665c54"
border_focused_color = "#d65d0e"
hl_bg = "#504945"
solid_bg = "#458588"
solid_fg = "#ebdbb2"
trusted = "#98971a"
remake = "#cc241d"
